"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

// ==================== أنواع البيانات ====================

interface Take {
  id: string;
  name: string;
  duration: number;
  recordedAt: Date;
  videoUrl?: string;
  thumbnailUrl?: string;
  notes: TakeNote[];
  score?: number;
  status: "recording" | "completed" | "exported";
}

interface TakeNote {
  id: string;
  timestamp: number;
  type: "emotion" | "delivery" | "timing" | "movement" | "improvement";
  content: string;
  severity: "positive" | "neutral" | "needs_work";
  autoGenerated: boolean;
}

interface TeleprompterSettings {
  speed: number;
  fontSize: number;
  mirrorMode: boolean;
  highlightCurrentLine: boolean;
  autoScroll: boolean;
  countdownSeconds: number;
}

interface ExportSettings {
  quality: "casting" | "high" | "medium";
  format: "mp4" | "mov" | "webm";
  includeSlate: boolean;
  slateDuration: number;
  actorName: string;
  projectName: string;
  roleName: string;
  agencyName: string;
}

interface ComparisonView {
  leftTakeId: string | null;
  rightTakeId: string | null;
  syncPlayback: boolean;
}

type ActiveTool = "teleprompter" | "recorder" | "comparison" | "notes" | "export";

// ==================== البيانات التجريبية ====================

const SAMPLE_SCRIPT = `المشهد الأول - غرفة المعيشة - نهاراً

تدخل سارة الغرفة بخطوات متثاقلة، تحمل في يدها رسالة مفتوحة.

سارة: (تنظر للرسالة بصدمة)
لا... هذا لا يمكن أن يكون حقيقياً.
كيف يمكنه أن يفعل هذا بعد كل هذه السنوات؟

(تجلس على الأريكة، تمسك الرسالة بيدين مرتجفتين)

سارة: (بصوت مختنق)
ظننت أننا كنا عائلة...
ظننت أن الماضي قد انتهى.

(تنهض فجأة، تمشي نحو النافذة)

سارة: (بحزم)
لكنني لن أسمح لهذا أن يدمر ما بنيته.
لقد تغيرت... وسأثبت ذلك.`;

const SAMPLE_TAKES: Take[] = [
  {
    id: "take-1",
    name: "Take 1 - أولي",
    duration: 125,
    recordedAt: new Date("2025-01-15T10:30:00"),
    thumbnailUrl: "/api/placeholder/320/180",
    notes: [
      {
        id: "n1",
        timestamp: 15,
        type: "emotion",
        content: "افتتاحية عاطفية قوية - الصدمة واضحة",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "n2",
        timestamp: 45,
        type: "delivery",
        content: "يمكن إبطاء الإيقاع هنا للتأثير الدرامي",
        severity: "needs_work",
        autoGenerated: true,
      },
      {
        id: "n3",
        timestamp: 90,
        type: "movement",
        content: "الانتقال للنافذة طبيعي ومقنع",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 78,
    status: "completed",
  },
  {
    id: "take-2",
    name: "Take 2 - تحسين",
    duration: 132,
    recordedAt: new Date("2025-01-15T10:45:00"),
    thumbnailUrl: "/api/placeholder/320/180",
    notes: [
      {
        id: "n4",
        timestamp: 20,
        type: "emotion",
        content: "عمق عاطفي ممتاز في لحظة الصدمة",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "n5",
        timestamp: 50,
        type: "timing",
        content: "التوقيت المثالي - الوقفة مؤثرة جداً",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "n6",
        timestamp: 100,
        type: "improvement",
        content: "النهاية القوية تحتاج مزيد من الحزم في الصوت",
        severity: "neutral",
        autoGenerated: true,
      },
    ],
    score: 85,
    status: "completed",
  },
  {
    id: "take-3",
    name: "Take 3 - نهائي",
    duration: 128,
    recordedAt: new Date("2025-01-15T11:00:00"),
    thumbnailUrl: "/api/placeholder/320/180",
    notes: [
      {
        id: "n7",
        timestamp: 18,
        type: "emotion",
        content: "أداء استثنائي - الصدق العاطفي واضح",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "n8",
        timestamp: 55,
        type: "delivery",
        content: "إلقاء مثالي مع تنوع نغمي رائع",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "n9",
        timestamp: 95,
        type: "movement",
        content: "لغة الجسد معبرة ومتناسقة مع الحوار",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 92,
    status: "completed",
  },
];

// ==================== المكون الرئيسي ====================

export const SelfTapeSuite: React.FC = () => {
  // الحالة الرئيسية
  const [activeTool, setActiveTool] = useState<ActiveTool>("teleprompter");
  const [scriptText, setScriptText] = useState(SAMPLE_SCRIPT);
  const [takes, setTakes] = useState<Take[]>(SAMPLE_TAKES);

  // حالة الإشعارات
  const [notification, setNotification] = useState<{
    type: "success" | "error" | "info";
    message: string;
  } | null>(null);

  // حالة Teleprompter
  const [teleprompterSettings, setTeleprompterSettings] = useState<TeleprompterSettings>({
    speed: 50,
    fontSize: 32,
    mirrorMode: false,
    highlightCurrentLine: true,
    autoScroll: true,
    countdownSeconds: 5,
  });
  const [teleprompterRunning, setTeleprompterRunning] = useState(false);
  const [teleprompterPosition, setTeleprompterPosition] = useState(0);
  const [countdown, setCountdown] = useState(0);

  // حالة التسجيل
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [currentTake, setCurrentTake] = useState<Take | null>(null);
  const recordingIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const teleprompterIntervalRef = useRef<NodeJS.Timeout | null>(null);

  // حالة المقارنة
  const [comparisonView, setComparisonView] = useState<ComparisonView>({
    leftTakeId: takes[0]?.id || null,
    rightTakeId: takes[1]?.id || null,
    syncPlayback: true,
  });

  // حالة التصدير
  const [exportSettings, setExportSettings] = useState<ExportSettings>({
    quality: "casting",
    format: "mp4",
    includeSlate: true,
    slateDuration: 5,
    actorName: "",
    projectName: "",
    roleName: "",
    agencyName: "",
  });
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);

  // التنظيف عند إلغاء التثبيت
  useEffect(() => {
    return () => {
      if (recordingIntervalRef.current) clearInterval(recordingIntervalRef.current);
      if (teleprompterIntervalRef.current) clearInterval(teleprompterIntervalRef.current);
    };
  }, []);

  // إخفاء الإشعارات تلقائياً
  useEffect(() => {
    if (notification) {
      const timer = setTimeout(() => setNotification(null), 4000);
      return () => clearTimeout(timer);
    }
    return undefined;
  }, [notification]);

  // عرض إشعار
  const showNotification = useCallback(
    (type: "success" | "error" | "info", message: string) => {
      setNotification({ type, message });
    },
    []
  );

  // ==================== دوال Teleprompter ====================

  const startTeleprompter = useCallback(() => {
    if (teleprompterSettings.countdownSeconds > 0) {
      setCountdown(teleprompterSettings.countdownSeconds);
      const countdownInterval = setInterval(() => {
        setCountdown((prev) => {
          if (prev <= 1) {
            clearInterval(countdownInterval);
            setTeleprompterRunning(true);
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    } else {
      setTeleprompterRunning(true);
    }
  }, [teleprompterSettings.countdownSeconds]);

  const stopTeleprompter = useCallback(() => {
    setTeleprompterRunning(false);
    setCountdown(0);
    if (teleprompterIntervalRef.current) {
      clearInterval(teleprompterIntervalRef.current);
    }
  }, []);

  const resetTeleprompter = useCallback(() => {
    stopTeleprompter();
    setTeleprompterPosition(0);
  }, [stopTeleprompter]);

  // تحريك Teleprompter
  useEffect(() => {
    if (teleprompterRunning && teleprompterSettings.autoScroll) {
      teleprompterIntervalRef.current = setInterval(() => {
        setTeleprompterPosition((prev) => {
          const maxPosition = 100;
          const newPosition = prev + teleprompterSettings.speed / 500;
          if (newPosition >= maxPosition) {
            setTeleprompterRunning(false);
            return maxPosition;
          }
          return newPosition;
        });
      }, 100);
    } else if (teleprompterIntervalRef.current) {
      clearInterval(teleprompterIntervalRef.current);
    }

    return () => {
      if (teleprompterIntervalRef.current) {
        clearInterval(teleprompterIntervalRef.current);
      }
    };
  }, [teleprompterRunning, teleprompterSettings.autoScroll, teleprompterSettings.speed]);

  // ==================== دوال التسجيل ====================

  const startRecording = useCallback(() => {
    const newTake: Take = {
      id: `take-${Date.now()}`,
      name: `Take ${takes.length + 1}`,
      duration: 0,
      recordedAt: new Date(),
      notes: [],
      status: "recording",
    };
    setCurrentTake(newTake);
    setIsRecording(true);
    setRecordingTime(0);

    recordingIntervalRef.current = setInterval(() => {
      setRecordingTime((prev) => prev + 1);
    }, 1000);

    // بدء Teleprompter تلقائياً
    startTeleprompter();

    showNotification("info", "🎬 بدأ التسجيل...");
  }, [takes.length, startTeleprompter, showNotification]);

  const stopRecording = useCallback(() => {
    setIsRecording(false);
    stopTeleprompter();

    if (recordingIntervalRef.current) {
      clearInterval(recordingIntervalRef.current);
    }

    if (currentTake) {
      const completedTake: Take = {
        ...currentTake,
        duration: recordingTime,
        status: "completed",
        notes: generateAutoNotes(recordingTime),
        score: Math.floor(Math.random() * 20) + 75,
      };
      setTakes((prev) => [...prev, completedTake]);
      setCurrentTake(null);
      showNotification("success", `✅ تم حفظ ${completedTake.name} بنجاح`);
    }

    setRecordingTime(0);
    resetTeleprompter();
  }, [currentTake, recordingTime, stopTeleprompter, resetTeleprompter, showNotification]);

  // توليد ملاحظات تلقائية
  const generateAutoNotes = (duration: number): TakeNote[] => {
    const noteTypes: TakeNote["type"][] = ["emotion", "delivery", "timing", "movement", "improvement"];
    const positiveComments = [
      "أداء عاطفي مقنع",
      "إيقاع ممتاز في الإلقاء",
      "تعبيرات وجه طبيعية",
      "حركة مسرحية سلسة",
      "صدق في الأداء",
    ];
    const neutralComments = [
      "يمكن تحسين التنوع النغمي",
      "جرب إضافة وقفة درامية هنا",
      "النظرة للكاميرا جيدة، جرب زاوية مختلفة",
      "حاول استخدام المساحة أكثر",
    ];

    const notes: TakeNote[] = [];
    const numNotes = Math.floor(Math.random() * 3) + 2;

    for (let i = 0; i < numNotes; i++) {
      const isPositive = Math.random() > 0.4;
      const noteType = noteTypes[Math.floor(Math.random() * noteTypes.length)] ?? "timing";
      const content = isPositive
        ? (positiveComments[Math.floor(Math.random() * positiveComments.length)] ?? "أداء جيد")
        : (neutralComments[Math.floor(Math.random() * neutralComments.length)] ?? "ملاحظة");
      notes.push({
        id: `auto-${Date.now()}-${i}`,
        timestamp: Math.floor((duration / numNotes) * (i + 0.5)),
        type: noteType,
        content,
        severity: isPositive ? "positive" : "neutral",
        autoGenerated: true,
      });
    }

    return notes;
  };

  // حذف Take
  const deleteTake = useCallback(
    (takeId: string) => {
      setTakes((prev) => prev.filter((t) => t.id !== takeId));
      showNotification("info", "تم حذف التسجيل");
    },
    [showNotification]
  );

  // ==================== دوال التصدير ====================

  const startExport = useCallback(
    async (takeId: string) => {
      const take = takes.find((t) => t.id === takeId);
      if (!take) return;

      setIsExporting(true);
      setExportProgress(0);

      // محاكاة عملية التصدير
      const exportSteps = [
        "تحضير الفيديو...",
        "إضافة Slate...",
        "ضبط الجودة...",
        "تحويل التنسيق...",
        "إنهاء التصدير...",
      ];

      for (let i = 0; i <= 100; i += 5) {
        await new Promise((resolve) => setTimeout(resolve, 150));
        setExportProgress(i);
      }

      setIsExporting(false);
      setExportProgress(0);
      showNotification(
        "success",
        `✅ تم تصدير "${take.name}" بجودة ${
          exportSettings.quality === "casting" ? "Casting" : exportSettings.quality
        }`
      );
    },
    [takes, exportSettings.quality, showNotification]
  );

  // ==================== تنسيق الوقت ====================

  const formatTime = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  // ==================== الحصول على Take ====================

  const getTakeById = (id: string | null): Take | undefined => {
    return takes.find((t) => t.id === id);
  };

  // ==================== واجهة المستخدم ====================

  return (
    <div className="min-h-screen bg-gradient-to-bl from-slate-900 via-purple-900 to-slate-900" dir="rtl">
      {/* شريط العنوان */}
      <header className="border-b border-purple-500/30 bg-black/30 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-red-500 to-pink-600 flex items-center justify-center">
                <span className="text-2xl">🎥</span>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white">Self-Tape Suite</h1>
                <p className="text-purple-300 text-sm">استوديو التسجيل الذاتي الاحترافي</p>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <Badge variant="outline" className="border-green-500 text-green-400">
                🚀 المرحلة الثالثة
              </Badge>
              <Button
                variant="outline"
                className="border-purple-500 text-purple-300 hover:bg-purple-500/20"
                onClick={() => (window.location.href = "/actorai-arabic")}
              >
                العودة للرئيسية
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* الإشعارات */}
      {notification && (
        <div className="fixed top-20 left-1/2 -translate-x-1/2 z-50 animate-in fade-in slide-in-from-top-5">
          <Alert
            className={`${
              notification.type === "success"
                ? "bg-green-500/20 border-green-500 text-green-300"
                : notification.type === "error"
                ? "bg-red-500/20 border-red-500 text-red-300"
                : "bg-blue-500/20 border-blue-500 text-blue-300"
            }`}
          >
            <AlertDescription className="text-lg">{notification.message}</AlertDescription>
          </Alert>
        </div>
      )}

      {/* المحتوى الرئيسي */}
      <main className="container mx-auto px-4 py-6">
        {/* شريط الأدوات */}
        <div className="flex flex-wrap gap-2 mb-6">
          {[
            { id: "teleprompter", label: "📜 Teleprompter", icon: "📜" },
            { id: "recorder", label: "🎬 التسجيل", icon: "🎬" },
            { id: "comparison", label: "⚖️ المقارنة", icon: "⚖️" },
            { id: "notes", label: "📝 الملاحظات", icon: "📝" },
            { id: "export", label: "📤 التصدير", icon: "📤" },
          ].map((tool) => (
            <Button
              key={tool.id}
              variant={activeTool === tool.id ? "default" : "outline"}
              className={`${
                activeTool === tool.id
                  ? "bg-purple-600 hover:bg-purple-700 text-white"
                  : "border-purple-500/50 text-purple-300 hover:bg-purple-500/20"
              }`}
              onClick={() => setActiveTool(tool.id as ActiveTool)}
            >
              {tool.label}
            </Button>
          ))}
        </div>

        {/* ==================== Teleprompter ذكي ==================== */}
        {activeTool === "teleprompter" && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* إعدادات Teleprompter */}
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>⚙️</span> إعدادات Teleprompter
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* السرعة */}
                <div className="space-y-2">
                  <Label className="text-purple-300">سرعة التمرير: {teleprompterSettings.speed}%</Label>
                  <Slider
                    value={[teleprompterSettings.speed]}
                    onValueChange={([value]) =>
                      setTeleprompterSettings((prev) => ({ ...prev, speed: value ?? prev.speed }))
                    }
                    min={10}
                    max={100}
                    step={5}
                    className="w-full"
                  />
                </div>

                {/* حجم الخط */}
                <div className="space-y-2">
                  <Label className="text-purple-300">حجم الخط: {teleprompterSettings.fontSize}px</Label>
                  <Slider
                    value={[teleprompterSettings.fontSize]}
                    onValueChange={([value]) =>
                      setTeleprompterSettings((prev) => ({ ...prev, fontSize: value ?? prev.fontSize }))
                    }
                    min={18}
                    max={72}
                    step={2}
                    className="w-full"
                  />
                </div>

                {/* العد التنازلي */}
                <div className="space-y-2">
                  <Label className="text-purple-300">
                    العد التنازلي: {teleprompterSettings.countdownSeconds} ثوان
                  </Label>
                  <Slider
                    value={[teleprompterSettings.countdownSeconds]}
                    onValueChange={([value]) =>
                      setTeleprompterSettings((prev) => ({ ...prev, countdownSeconds: value ?? prev.countdownSeconds }))
                    }
                    min={0}
                    max={10}
                    step={1}
                    className="w-full"
                  />
                </div>

                {/* خيارات إضافية */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label className="text-purple-300">وضع المرآة</Label>
                    <Button
                      variant="outline"
                      size="sm"
                      className={`${
                        teleprompterSettings.mirrorMode
                          ? "bg-purple-600 border-purple-600"
                          : "border-purple-500/50"
                      } text-white`}
                      onClick={() =>
                        setTeleprompterSettings((prev) => ({
                          ...prev,
                          mirrorMode: !prev.mirrorMode,
                        }))
                      }
                    >
                      {teleprompterSettings.mirrorMode ? "✓ مفعل" : "معطل"}
                    </Button>
                  </div>

                  <div className="flex items-center justify-between">
                    <Label className="text-purple-300">تمييز السطر الحالي</Label>
                    <Button
                      variant="outline"
                      size="sm"
                      className={`${
                        teleprompterSettings.highlightCurrentLine
                          ? "bg-purple-600 border-purple-600"
                          : "border-purple-500/50"
                      } text-white`}
                      onClick={() =>
                        setTeleprompterSettings((prev) => ({
                          ...prev,
                          highlightCurrentLine: !prev.highlightCurrentLine,
                        }))
                      }
                    >
                      {teleprompterSettings.highlightCurrentLine ? "✓ مفعل" : "معطل"}
                    </Button>
                  </div>
                </div>

                {/* أزرار التحكم */}
                <div className="flex gap-2 pt-4">
                  {!teleprompterRunning ? (
                    <Button
                      className="flex-1 bg-green-600 hover:bg-green-700"
                      onClick={startTeleprompter}
                      disabled={countdown > 0}
                    >
                      {countdown > 0 ? `${countdown}...` : "▶️ تشغيل"}
                    </Button>
                  ) : (
                    <Button className="flex-1 bg-yellow-600 hover:bg-yellow-700" onClick={stopTeleprompter}>
                      ⏸️ إيقاف مؤقت
                    </Button>
                  )}
                  <Button
                    variant="outline"
                    className="border-purple-500/50 text-purple-300"
                    onClick={resetTeleprompter}
                  >
                    🔄 إعادة
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* شاشة Teleprompter */}
            <Card className="lg:col-span-2 bg-black border-purple-500/30 min-h-[500px]">
              <CardContent className="p-0 h-full">
                <div
                  className={`h-full overflow-hidden relative ${
                    teleprompterSettings.mirrorMode ? "scale-x-[-1]" : ""
                  }`}
                >
                  {/* العد التنازلي */}
                  {countdown > 0 && (
                    <div className="absolute inset-0 flex items-center justify-center bg-black/80 z-10">
                      <span className="text-9xl font-bold text-purple-500 animate-pulse">{countdown}</span>
                    </div>
                  )}

                  {/* مؤشر التقدم */}
                  <div className="absolute top-0 left-0 right-0 h-1 bg-purple-900">
                    <div
                      className="h-full bg-purple-500 transition-all duration-100"
                      style={{ width: `${teleprompterPosition}%` }}
                    />
                  </div>

                  {/* النص */}
                  <div
                    className="p-8 text-white leading-relaxed transition-transform duration-100"
                    style={{
                      fontSize: `${teleprompterSettings.fontSize}px`,
                      transform: `translateY(-${teleprompterPosition * 3}px)`,
                    }}
                  >
                    {scriptText.split("\n").map((line, index) => {
                      const lineProgress = (index / scriptText.split("\n").length) * 100;
                      const isCurrentLine =
                        teleprompterSettings.highlightCurrentLine &&
                        Math.abs(lineProgress - teleprompterPosition) < 10;

                      return (
                        <p
                          key={index}
                          className={`mb-4 transition-all duration-300 ${
                            isCurrentLine
                              ? "text-yellow-300 scale-105 bg-yellow-500/10 px-4 py-2 rounded-lg"
                              : lineProgress < teleprompterPosition
                              ? "text-gray-500"
                              : "text-white"
                          }`}
                        >
                          {line || "\u00A0"}
                        </p>
                      );
                    })}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* محرر النص */}
            <Card className="lg:col-span-3 bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>✏️</span> النص المراد قراءته
                </CardTitle>
                <CardDescription className="text-purple-300">
                  أدخل أو الصق نص المشهد الذي تريد تسجيله
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={scriptText}
                  onChange={(e) => setScriptText(e.target.value)}
                  className="min-h-[200px] bg-slate-900/50 border-purple-500/30 text-white text-lg"
                  placeholder="أدخل نص المشهد هنا..."
                  dir="rtl"
                />
              </CardContent>
            </Card>
          </div>
        )}

        {/* ==================== تسجيل Takes متعددة ==================== */}
        {activeTool === "recorder" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* منطقة التسجيل */}
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>🎬</span> استوديو التسجيل
                </CardTitle>
                <CardDescription className="text-purple-300">
                  سجل Takes متعددة وقارن بينها
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* شاشة المعاينة */}
                <div className="aspect-video bg-black rounded-xl border-2 border-purple-500/30 flex items-center justify-center relative overflow-hidden">
                  {isRecording && (
                    <div className="absolute top-4 right-4 flex items-center gap-2">
                      <div className="w-4 h-4 bg-red-500 rounded-full animate-pulse" />
                      <span className="text-red-400 font-mono text-lg">{formatTime(recordingTime)}</span>
                    </div>
                  )}

                  <div className="text-center">
                    <div className="w-24 h-24 rounded-full bg-purple-500/20 flex items-center justify-center mx-auto mb-4">
                      <span className="text-5xl">{isRecording ? "🔴" : "📹"}</span>
                    </div>
                    <p className="text-gray-400">
                      {isRecording ? "جاري التسجيل..." : "معاينة الكاميرا"}
                    </p>
                  </div>

                  {/* مصغر Teleprompter */}
                  {isRecording && (
                    <div className="absolute bottom-0 left-0 right-0 bg-black/70 p-3 text-white text-center">
                      <p className="text-lg line-clamp-2">{scriptText.split("\n")[0]}</p>
                    </div>
                  )}
                </div>

                {/* أزرار التحكم */}
                <div className="flex gap-3 justify-center">
                  {!isRecording ? (
                    <Button
                      size="lg"
                      className="bg-red-600 hover:bg-red-700 text-white px-8 py-6 text-xl"
                      onClick={startRecording}
                    >
                      🎬 بدء التسجيل
                    </Button>
                  ) : (
                    <Button
                      size="lg"
                      className="bg-gray-600 hover:bg-gray-700 text-white px-8 py-6 text-xl"
                      onClick={stopRecording}
                    >
                      ⏹️ إنهاء التسجيل
                    </Button>
                  )}
                </div>

                {/* إحصائيات الجلسة */}
                <div className="grid grid-cols-3 gap-4 pt-4 border-t border-purple-500/30">
                  <div className="text-center">
                    <p className="text-3xl font-bold text-purple-400">{takes.length}</p>
                    <p className="text-sm text-gray-400">إجمالي Takes</p>
                  </div>
                  <div className="text-center">
                    <p className="text-3xl font-bold text-green-400">
                      {takes.length > 0 ? Math.max(...takes.map((t) => t.score || 0)) : 0}%
                    </p>
                    <p className="text-sm text-gray-400">أعلى تقييم</p>
                  </div>
                  <div className="text-center">
                    <p className="text-3xl font-bold text-blue-400">
                      {formatTime(takes.reduce((acc, t) => acc + t.duration, 0))}
                    </p>
                    <p className="text-sm text-gray-400">إجمالي الوقت</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* قائمة Takes */}
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>📋</span> التسجيلات ({takes.length})
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3 max-h-[500px] overflow-y-auto">
                  {takes.length === 0 ? (
                    <div className="text-center py-12 text-gray-400">
                      <span className="text-5xl mb-4 block">🎬</span>
                      <p>لا توجد تسجيلات بعد</p>
                      <p className="text-sm">ابدأ بتسجيل أول Take</p>
                    </div>
                  ) : (
                    takes.map((take, index) => (
                      <div
                        key={take.id}
                        className="bg-slate-900/50 rounded-xl p-4 border border-purple-500/20 hover:border-purple-500/50 transition-all"
                      >
                        <div className="flex items-start justify-between mb-3">
                          <div>
                            <h4 className="text-white font-medium flex items-center gap-2">
                              {take.name}
                              {take.score && take.score >= 85 && (
                                <Badge className="bg-green-500/20 text-green-400 text-xs">⭐ ممتاز</Badge>
                              )}
                            </h4>
                            <p className="text-sm text-gray-400">
                              {take.recordedAt.toLocaleTimeString("ar-EG")} • {formatTime(take.duration)}
                            </p>
                          </div>
                          {take.score && (
                            <div
                              className={`text-2xl font-bold ${
                                take.score >= 85
                                  ? "text-green-400"
                                  : take.score >= 70
                                  ? "text-yellow-400"
                                  : "text-red-400"
                              }`}
                            >
                              {take.score}%
                            </div>
                          )}
                        </div>

                        {/* ملاحظات مختصرة */}
                        {take.notes.length > 0 && (
                          <div className="mb-3">
                            <p className="text-xs text-purple-300 mb-1">
                              {take.notes.length} ملاحظات تلقائية
                            </p>
                            <p className="text-sm text-gray-300 line-clamp-1">
                              {take.notes[0]?.content}
                            </p>
                          </div>
                        )}

                        {/* أزرار الإجراءات */}
                        <div className="flex gap-2">
                          <Button
                            size="sm"
                            variant="outline"
                            className="flex-1 border-purple-500/50 text-purple-300 hover:bg-purple-500/20"
                            onClick={() => {
                              setActiveTool("notes");
                            }}
                          >
                            📝 الملاحظات
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            className="flex-1 border-green-500/50 text-green-300 hover:bg-green-500/20"
                            onClick={() => startExport(take.id)}
                          >
                            📤 تصدير
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            className="border-red-500/50 text-red-300 hover:bg-red-500/20"
                            onClick={() => deleteTake(take.id)}
                          >
                            🗑️
                          </Button>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* ==================== مقارنة جنب-لجنب ==================== */}
        {activeTool === "comparison" && (
          <div className="space-y-6">
            {/* اختيار Takes للمقارنة */}
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>⚖️</span> مقارنة Takes جنباً إلى جنب
                </CardTitle>
                <CardDescription className="text-purple-300">
                  اختر تسجيلين لمقارنتهما ومشاهدة الفروقات
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-end">
                  <div>
                    <Label className="text-purple-300 mb-2 block">Take الأيسر</Label>
                    <Select
                      value={comparisonView.leftTakeId || ""}
                      onValueChange={(value) =>
                        setComparisonView((prev) => ({ ...prev, leftTakeId: value }))
                      }
                    >
                      <SelectTrigger className="bg-slate-900/50 border-purple-500/30 text-white">
                        <SelectValue placeholder="اختر Take" />
                      </SelectTrigger>
                      <SelectContent className="bg-slate-900 border-purple-500/30">
                        {takes.map((take) => (
                          <SelectItem key={take.id} value={take.id} className="text-white">
                            {take.name} ({take.score}%)
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="text-center">
                    <Button
                      variant="outline"
                      className={`border-purple-500/50 ${
                        comparisonView.syncPlayback ? "bg-purple-600" : ""
                      } text-white`}
                      onClick={() =>
                        setComparisonView((prev) => ({
                          ...prev,
                          syncPlayback: !prev.syncPlayback,
                        }))
                      }
                    >
                      {comparisonView.syncPlayback ? "🔗 متزامن" : "🔓 منفصل"}
                    </Button>
                  </div>

                  <div>
                    <Label className="text-purple-300 mb-2 block">Take الأيمن</Label>
                    <Select
                      value={comparisonView.rightTakeId || ""}
                      onValueChange={(value) =>
                        setComparisonView((prev) => ({ ...prev, rightTakeId: value }))
                      }
                    >
                      <SelectTrigger className="bg-slate-900/50 border-purple-500/30 text-white">
                        <SelectValue placeholder="اختر Take" />
                      </SelectTrigger>
                      <SelectContent className="bg-slate-900 border-purple-500/30">
                        {takes.map((take) => (
                          <SelectItem key={take.id} value={take.id} className="text-white">
                            {take.name} ({take.score}%)
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* شاشات المقارنة */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Take الأيسر */}
              <Card className="bg-slate-800/50 border-purple-500/30">
                <CardHeader className="pb-2">
                  <CardTitle className="text-white text-lg">
                    {getTakeById(comparisonView.leftTakeId)?.name || "اختر Take"}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="aspect-video bg-black rounded-lg flex items-center justify-center mb-4">
                    <span className="text-6xl">📹</span>
                  </div>
                  {comparisonView.leftTakeId && (
                    <div className="space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-400">التقييم:</span>
                        <span className="text-green-400 font-bold">
                          {getTakeById(comparisonView.leftTakeId)?.score}%
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-400">المدة:</span>
                        <span className="text-white">
                          {formatTime(getTakeById(comparisonView.leftTakeId)?.duration || 0)}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-400">الملاحظات:</span>
                        <span className="text-purple-300">
                          {getTakeById(comparisonView.leftTakeId)?.notes.length} ملاحظة
                        </span>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Take الأيمن */}
              <Card className="bg-slate-800/50 border-purple-500/30">
                <CardHeader className="pb-2">
                  <CardTitle className="text-white text-lg">
                    {getTakeById(comparisonView.rightTakeId)?.name || "اختر Take"}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="aspect-video bg-black rounded-lg flex items-center justify-center mb-4">
                    <span className="text-6xl">📹</span>
                  </div>
                  {comparisonView.rightTakeId && (
                    <div className="space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-400">التقييم:</span>
                        <span className="text-green-400 font-bold">
                          {getTakeById(comparisonView.rightTakeId)?.score}%
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-400">المدة:</span>
                        <span className="text-white">
                          {formatTime(getTakeById(comparisonView.rightTakeId)?.duration || 0)}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-400">الملاحظات:</span>
                        <span className="text-purple-300">
                          {getTakeById(comparisonView.rightTakeId)?.notes.length} ملاحظة
                        </span>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>

            {/* ملخص المقارنة */}
            {comparisonView.leftTakeId && comparisonView.rightTakeId && (
              <Card className="bg-slate-800/50 border-purple-500/30">
                <CardHeader>
                  <CardTitle className="text-white flex items-center gap-2">
                    <span>📊</span> ملخص المقارنة
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="text-center p-4 bg-slate-900/50 rounded-xl">
                      <p className="text-gray-400 text-sm mb-2">فرق التقييم</p>
                      <p
                        className={`text-3xl font-bold ${
                          (getTakeById(comparisonView.rightTakeId)?.score || 0) >
                          (getTakeById(comparisonView.leftTakeId)?.score || 0)
                            ? "text-green-400"
                            : "text-red-400"
                        }`}
                      >
                        {(getTakeById(comparisonView.rightTakeId)?.score || 0) -
                          (getTakeById(comparisonView.leftTakeId)?.score || 0) >
                        0
                          ? "+"
                          : ""}
                        {(getTakeById(comparisonView.rightTakeId)?.score || 0) -
                          (getTakeById(comparisonView.leftTakeId)?.score || 0)}
                        %
                      </p>
                    </div>
                    <div className="text-center p-4 bg-slate-900/50 rounded-xl">
                      <p className="text-gray-400 text-sm mb-2">فرق المدة</p>
                      <p className="text-3xl font-bold text-purple-400">
                        {Math.abs(
                          (getTakeById(comparisonView.rightTakeId)?.duration || 0) -
                            (getTakeById(comparisonView.leftTakeId)?.duration || 0)
                        )}
                        ث
                      </p>
                    </div>
                    <div className="text-center p-4 bg-slate-900/50 rounded-xl">
                      <p className="text-gray-400 text-sm mb-2">الأفضل</p>
                      <p className="text-xl font-bold text-yellow-400">
                        {(getTakeById(comparisonView.rightTakeId)?.score || 0) >
                        (getTakeById(comparisonView.leftTakeId)?.score || 0)
                          ? getTakeById(comparisonView.rightTakeId)?.name
                          : getTakeById(comparisonView.leftTakeId)?.name}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        )}

        {/* ==================== الملاحظات التلقائية ==================== */}
        {activeTool === "notes" && (
          <div className="space-y-6">
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>📝</span> الملاحظات التلقائية للأداء
                </CardTitle>
                <CardDescription className="text-purple-300">
                  ملاحظات مُولَّدة بالذكاء الاصطناعي لتحسين أدائك
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Tabs defaultValue={takes[0]?.id ?? ""} className="w-full">
                  <TabsList className="bg-slate-900/50 border border-purple-500/30 mb-4 flex-wrap h-auto gap-2 p-2">
                    {takes.map((take) => (
                      <TabsTrigger
                        key={take.id}
                        value={take.id}
                        className="data-[state=active]:bg-purple-600 text-white"
                      >
                        {take.name}
                      </TabsTrigger>
                    ))}
                  </TabsList>

                  {takes.map((take) => (
                    <TabsContent key={take.id} value={take.id}>
                      <div className="space-y-4">
                        {/* ملخص الأداء */}
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                          <div className="bg-slate-900/50 rounded-xl p-4 text-center">
                            <p className="text-gray-400 text-sm">التقييم العام</p>
                            <p
                              className={`text-3xl font-bold ${
                                (take.score || 0) >= 85
                                  ? "text-green-400"
                                  : (take.score || 0) >= 70
                                  ? "text-yellow-400"
                                  : "text-red-400"
                              }`}
                            >
                              {take.score}%
                            </p>
                          </div>
                          <div className="bg-slate-900/50 rounded-xl p-4 text-center">
                            <p className="text-gray-400 text-sm">الملاحظات الإيجابية</p>
                            <p className="text-3xl font-bold text-green-400">
                              {take.notes.filter((n) => n.severity === "positive").length}
                            </p>
                          </div>
                          <div className="bg-slate-900/50 rounded-xl p-4 text-center">
                            <p className="text-gray-400 text-sm">تحتاج تحسين</p>
                            <p className="text-3xl font-bold text-yellow-400">
                              {take.notes.filter((n) => n.severity === "needs_work").length}
                            </p>
                          </div>
                          <div className="bg-slate-900/50 rounded-xl p-4 text-center">
                            <p className="text-gray-400 text-sm">المدة</p>
                            <p className="text-3xl font-bold text-purple-400">
                              {formatTime(take.duration)}
                            </p>
                          </div>
                        </div>

                        {/* قائمة الملاحظات */}
                        <div className="space-y-3">
                          {take.notes.map((note) => (
                            <div
                              key={note.id}
                              className={`p-4 rounded-xl border ${
                                note.severity === "positive"
                                  ? "bg-green-500/10 border-green-500/30"
                                  : note.severity === "needs_work"
                                  ? "bg-yellow-500/10 border-yellow-500/30"
                                  : "bg-slate-900/50 border-purple-500/30"
                              }`}
                            >
                              <div className="flex items-start justify-between mb-2">
                                <div className="flex items-center gap-2">
                                  <Badge
                                    className={`${
                                      note.type === "emotion"
                                        ? "bg-pink-500/20 text-pink-300"
                                        : note.type === "delivery"
                                        ? "bg-blue-500/20 text-blue-300"
                                        : note.type === "timing"
                                        ? "bg-purple-500/20 text-purple-300"
                                        : note.type === "movement"
                                        ? "bg-orange-500/20 text-orange-300"
                                        : "bg-cyan-500/20 text-cyan-300"
                                    }`}
                                  >
                                    {note.type === "emotion"
                                      ? "💫 عاطفة"
                                      : note.type === "delivery"
                                      ? "🎤 إلقاء"
                                      : note.type === "timing"
                                      ? "⏱️ توقيت"
                                      : note.type === "movement"
                                      ? "🎭 حركة"
                                      : "💡 تحسين"}
                                  </Badge>
                                  <span className="text-gray-400 text-sm">
                                    @ {formatTime(note.timestamp)}
                                  </span>
                                </div>
                                {note.autoGenerated && (
                                  <Badge variant="outline" className="border-purple-500/50 text-purple-300 text-xs">
                                    🤖 AI
                                  </Badge>
                                )}
                              </div>
                              <p className="text-white">{note.content}</p>
                            </div>
                          ))}
                        </div>

                        {/* إضافة ملاحظة يدوية */}
                        <div className="pt-4 border-t border-purple-500/30">
                          <Label className="text-purple-300 mb-2 block">إضافة ملاحظة يدوية</Label>
                          <div className="flex gap-2">
                            <Input
                              placeholder="اكتب ملاحظتك هنا..."
                              className="bg-slate-900/50 border-purple-500/30 text-white"
                            />
                            <Button className="bg-purple-600 hover:bg-purple-700">إضافة</Button>
                          </div>
                        </div>
                      </div>
                    </TabsContent>
                  ))}
                </Tabs>
              </CardContent>
            </Card>
          </div>
        )}

        {/* ==================== التصدير بجودة Casting ==================== */}
        {activeTool === "export" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* إعدادات التصدير */}
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>⚙️</span> إعدادات التصدير
                </CardTitle>
                <CardDescription className="text-purple-300">
                  خصص إعدادات التصدير لتناسب متطلبات Casting
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* جودة التصدير */}
                <div className="space-y-2">
                  <Label className="text-purple-300">جودة التصدير</Label>
                  <Select
                    value={exportSettings.quality}
                    onValueChange={(value: "casting" | "high" | "medium") =>
                      setExportSettings((prev) => ({ ...prev, quality: value }))
                    }
                  >
                    <SelectTrigger className="bg-slate-900/50 border-purple-500/30 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-900 border-purple-500/30">
                      <SelectItem value="casting" className="text-white">
                        🎬 Casting Quality (1080p, H.264)
                      </SelectItem>
                      <SelectItem value="high" className="text-white">
                        📺 High Quality (4K)
                      </SelectItem>
                      <SelectItem value="medium" className="text-white">
                        📱 Medium (720p)
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* تنسيق الملف */}
                <div className="space-y-2">
                  <Label className="text-purple-300">تنسيق الملف</Label>
                  <Select
                    value={exportSettings.format}
                    onValueChange={(value: "mp4" | "mov" | "webm") =>
                      setExportSettings((prev) => ({ ...prev, format: value }))
                    }
                  >
                    <SelectTrigger className="bg-slate-900/50 border-purple-500/30 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-900 border-purple-500/30">
                      <SelectItem value="mp4" className="text-white">
                        MP4 (الأكثر توافقاً)
                      </SelectItem>
                      <SelectItem value="mov" className="text-white">
                        MOV (جودة عالية)
                      </SelectItem>
                      <SelectItem value="webm" className="text-white">
                        WebM (للويب)
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* Slate */}
                <div className="space-y-4 p-4 bg-slate-900/50 rounded-xl">
                  <div className="flex items-center justify-between">
                    <Label className="text-purple-300">إضافة Slate</Label>
                    <Button
                      variant="outline"
                      size="sm"
                      className={`${
                        exportSettings.includeSlate ? "bg-purple-600 border-purple-600" : "border-purple-500/50"
                      } text-white`}
                      onClick={() =>
                        setExportSettings((prev) => ({
                          ...prev,
                          includeSlate: !prev.includeSlate,
                        }))
                      }
                    >
                      {exportSettings.includeSlate ? "✓ مفعل" : "معطل"}
                    </Button>
                  </div>

                  {exportSettings.includeSlate && (
                    <div className="space-y-4 pt-4 border-t border-purple-500/30">
                      <div>
                        <Label className="text-purple-300 text-sm">اسم الممثل</Label>
                        <Input
                          value={exportSettings.actorName}
                          onChange={(e) =>
                            setExportSettings((prev) => ({ ...prev, actorName: e.target.value }))
                          }
                          placeholder="أدخل اسمك"
                          className="bg-slate-800/50 border-purple-500/30 text-white mt-1"
                        />
                      </div>
                      <div>
                        <Label className="text-purple-300 text-sm">اسم المشروع</Label>
                        <Input
                          value={exportSettings.projectName}
                          onChange={(e) =>
                            setExportSettings((prev) => ({ ...prev, projectName: e.target.value }))
                          }
                          placeholder="اسم الفيلم / المسلسل"
                          className="bg-slate-800/50 border-purple-500/30 text-white mt-1"
                        />
                      </div>
                      <div>
                        <Label className="text-purple-300 text-sm">اسم الدور</Label>
                        <Input
                          value={exportSettings.roleName}
                          onChange={(e) =>
                            setExportSettings((prev) => ({ ...prev, roleName: e.target.value }))
                          }
                          placeholder="الشخصية"
                          className="bg-slate-800/50 border-purple-500/30 text-white mt-1"
                        />
                      </div>
                      <div>
                        <Label className="text-purple-300 text-sm">الوكالة (اختياري)</Label>
                        <Input
                          value={exportSettings.agencyName}
                          onChange={(e) =>
                            setExportSettings((prev) => ({ ...prev, agencyName: e.target.value }))
                          }
                          placeholder="اسم الوكالة"
                          className="bg-slate-800/50 border-purple-500/30 text-white mt-1"
                        />
                      </div>
                      <div>
                        <Label className="text-purple-300 text-sm">
                          مدة Slate: {exportSettings.slateDuration} ثوان
                        </Label>
                        <Slider
                          value={[exportSettings.slateDuration]}
                          onValueChange={([value]) =>
                            setExportSettings((prev) => ({ ...prev, slateDuration: value ?? prev.slateDuration }))
                          }
                          min={3}
                          max={10}
                          step={1}
                          className="w-full mt-2"
                        />
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* اختيار وتصدير Takes */}
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <span>📤</span> تصدير التسجيلات
                </CardTitle>
              </CardHeader>
              <CardContent>
                {isExporting ? (
                  <div className="text-center py-12">
                    <div className="w-20 h-20 rounded-full border-4 border-purple-500 border-t-transparent animate-spin mx-auto mb-4" />
                    <p className="text-white text-xl mb-4">جاري التصدير...</p>
                    <Progress value={exportProgress} className="w-full h-3" />
                    <p className="text-purple-300 mt-2">{exportProgress}%</p>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {takes.map((take) => (
                      <div
                        key={take.id}
                        className="bg-slate-900/50 rounded-xl p-4 border border-purple-500/20"
                      >
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="text-white font-medium">{take.name}</h4>
                            <p className="text-sm text-gray-400">
                              {formatTime(take.duration)} • تقييم: {take.score}%
                            </p>
                          </div>
                          <Button
                            className="bg-green-600 hover:bg-green-700"
                            onClick={() => startExport(take.id)}
                          >
                            📤 تصدير
                          </Button>
                        </div>
                      </div>
                    ))}

                    {takes.length > 1 && (
                      <div className="pt-4 border-t border-purple-500/30">
                        <Button
                          className="w-full bg-purple-600 hover:bg-purple-700"
                          onClick={() => {
                            const bestTake = takes.reduce((best, current) =>
                              (current.score || 0) > (best.score || 0) ? current : best
                            );
                            startExport(bestTake.id);
                          }}
                        >
                          ⭐ تصدير أفضل Take تلقائياً
                        </Button>
                      </div>
                    )}
                  </div>
                )}

                {/* معاينة Slate */}
                {exportSettings.includeSlate && exportSettings.actorName && (
                  <div className="mt-6 pt-6 border-t border-purple-500/30">
                    <Label className="text-purple-300 mb-3 block">معاينة Slate</Label>
                    <div className="aspect-video bg-black rounded-xl p-8 flex flex-col items-center justify-center text-center">
                      <h2 className="text-3xl font-bold text-white mb-2">{exportSettings.actorName}</h2>
                      {exportSettings.projectName && (
                        <p className="text-xl text-purple-300">{exportSettings.projectName}</p>
                      )}
                      {exportSettings.roleName && (
                        <p className="text-lg text-gray-400">الدور: {exportSettings.roleName}</p>
                      )}
                      {exportSettings.agencyName && (
                        <p className="text-sm text-gray-500 mt-4">{exportSettings.agencyName}</p>
                      )}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-purple-500/30 bg-black/30 mt-8">
        <div className="container mx-auto px-4 py-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-gray-400 text-sm">
              Self-Tape Suite © 2025 - جزء من منصة ActorAI العربية
            </p>
            <div className="flex items-center gap-4">
              <Badge variant="outline" className="border-purple-500/50 text-purple-300">
                المرحلة الثالثة - مستقبلية
              </Badge>
              <Badge variant="outline" className="border-green-500/50 text-green-300">
                v1.0.0
              </Badge>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default SelfTapeSuite;
